### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by dimqua** [bhb27/KA27#2]
Please consider to add the app to F-Droid.

See also: https://gitlab.com/fdroid/rfp/issues/272

**Comment by fgl27** [comment]
I don't wanna.

I prefer to keep this project XDA only... I don't wanna any  kind of conflict with original kernel adiutor from
https://github.com/Grarak/KernelAdiutor

**Comment by KOLANICH** [comment]
@fgl27, the author of the original app has archived it in 2018, most of the forks have stopped any activity in 2019.

**Comment by fgl27** [comment]
So? what do you mean?

Is an open source project this is my personal version of it, I maintain it if I wanna in my own way, that means no F-Droid support.
